-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 21:12:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database` DEFAULT CHARACTER SET utf8 ;
USE `database` ;

-- -----------------------------------------------------
-- Table `database`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `CategoryType` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `database`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `database`.`Books` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `idUser` INT NULL,
  `idCategory` INT NULL,
  `Image` BLOB NULL,
  `Price` FLOAT UNSIGNED NULL,
  PRIMARY KEY (`idBook`),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idCategory_idx` (`idCategory` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `database`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCategory`
    FOREIGN KEY (`idCategory`)
    REFERENCES `database`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
